  version: '3.8'

  services:
    db:
      image: mysql:8.0
      container_name: mysql_db
      ports:
        - "3306:3306"
      env_file: .env  # 환경 변수를 .env 파일에서 로드
      environment:
        TZ: Asia/Seoul  # 타임존 설정
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - backend
      restart: always  # 예기치 않은 종료 시 자동 재시작
      
    web:
      build: .
      container_name: fastapi_app
      ports:
        - "8000:8000"
      env_file: .env  # 환경 변수를 .env 파일에서 로드
      depends_on:
        - db
      networks:
        - backend
      restart: always  # 예기치 않은 종료 시 자동 재시작

  volumes:
    db_data:
      driver: local

  networks:
    backend:
